server: 
   port: 80
   servlet:
      context-path: /
      
mybatis:
   type-aliases-package: com.jinqshen.weixin.pojo
   config-location: classpath:mybatis/mybatis-config.xml
   mapper-locations: classpath:mybatis/mapper/*.xml
    
spring:   
   datasource:
      url: jdbc:mysql://localhost:3306/finaco?serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Sjq!580230
          
   redis:
      host: 127.0.0.1
      password: 580230
      port: 6379
      pool:
         max-idle: 100
         min-idle: 1
         max-active: 1000
         max-wait: -1
         
   thymeleaf:
      cache: false